### PR TITLE
lib: add extended options for HTTP

### LINKED ISSUE #84: Add ability to configure how large a response is allowed to be and fail the request if it's larger
Context:
Some APIs do not have a constant response size. A large response could cause failure due to exhaustion of memory.

Request:
To add a new http request  or augment the current request to take configuration to control behavior. For instance we could include a max response configuration, which when present wraps the resp.Body in an 
io.LimitedReader like so
```

	type limitBody struct {
		io.Reader
		io.Closer
	}
	body := limitBody{
		Reader: io.LimitReader(resp.Body, n),
		Closer: resp.Body,
	}

```

Goal:
1. To protect the process from OOMing
2. To be able to capture a failed request in a cel script and retry the request with a lower batch size. This may be not be possible given the constraints of cel

### PR DESCRIPTION
**Pull request by efd6**
Please take a look.

Closes #84

### CODE REVIEW

File: lib/http.go [hunk 1]
```diff
@@ -663,7 +699,7 @@ func reqToMap(req *http.Request, url, body ref.Val) (map[string]interface{}, err
 		rm["Trailer"] = req.Trailer
 	}
 	if req.Response != nil {
-		resp, err := respToMap(req.Response)
+		resp, err := respToMap(req.Response, -1)
```
Comment (StacieClark-Elastic) [inline lib/http.go]: Currently, limitBody is not handling a negative parameter. I would expect a negative parameter to result in an error.
func limitBody(r io.ReadCloser, n int64) io.ReadCloser {
	if n == 0 {
		return r
	}
	return &limitedReadCloser{r, n}
}

File: lib/http.go [hunk 2]
```diff
@@ -685,7 +721,7 @@ func respToMap(resp *http.Response) (map[string]interface{}, error) {
 		"Uncompressed":  resp.Uncompressed,
 	}
 	var buf bytes.Buffer
-	_, err := io.Copy(&buf, resp.Body)
+	_, err := io.Copy(&buf, limitBody(resp.Body, max))
```
Comment (StacieClark-Elastic) [inline lib/http.go:724]: http.MaxBytesReader looks like it would work here. Any reason why you chose to not use it?

**Review by StacieClark-Elastic — CHANGES_REQUESTED** [review]

File: lib/http.go (hunk 1 above)
Comment (efd6) [reply lib/http.go]: The documented behaviour of `limitBody` is to not limit when the limit value is zero. The documented behaviour of the `io.ReadCloser` that it returns is to "stop… with ErrBodyTooBig after n bytes unless n is zero". Any number of bytes is after n < 0. The approach here allows the zero value to signal that no limit is in place. There is a hole; it is not possible to limit to exactly zero. I'm OK with that.

File: lib/http.go (hunk 2 above)
Comment (efd6) [reply lib/http.go:724]: `http.MaxBytesReader` handles request bodies and is a handler (it has the `http.ResponseWriter` param). It returns [errors that would be confusing](https://cs.opensource.google/go/go/+/refs/tags/go1.24.2:src/net/http/request.go;l=1200).

File: lib/http.go (hunk 1 above)
Comment (efd6) [reply lib/http.go:702]: We could get rid of the hole by setting `n = max(0, n)` after the zero check.

Comment (StacieClark-Elastic) [reply lib/http.go]: But you are passing in -1, not 0. The -1  is passed in as n and a limitedReadCloser is returned instead of the ReadCloser. When you go to decode you hit this guard clause
``
func (l *limitedReadCloser) Read(p []byte) (n int, err error) {
	if l.n <= 0 {
		return 0, ErrBodyTooBig
	} ``

File: lib/http.go (hunk 2 above)
Comment (StacieClark-Elastic) [reply lib/http.go:724]: this is the usage I was thinking of https://go.dev/play/p/2GlegE7VPZC

Comment (efd6) [reply lib/http.go:724]: The first line of output shows why this would be confusing:
```
When body is large: [0 1 2 3] http: request body too large
```
The local implementation here is small and is focused exactly on what we want to achieve while using `http.MaxBytesReader` requires that it be shoehorned in.

File: lib/http.go (hunk 1 above)
Comment (efd6) [reply lib/http.go]: You are correct. This should be using `l.option.MaxBodySize`'s value. I misrecalled what `http.Request.Response` is used for.

Comment (efd6) [reply lib/http.go]: PTAL

**Comment by StacieClark-Elastic** [comment]
LGTM

**Review by StacieClark-Elastic — APPROVED** [review]
